site_name: HocSphere

theme:
  favicon: assets/eagle.png
  palette:
    primary: black 
    accent: red
  font:
    text: Roboto
  name: material
  icon:
    admonition:
      note: octicons/tag-16
      abstract: octicons/checklist-16
      info: octicons/info-16
      tip: octicons/squirrel-16
      success: octicons/check-16
      question: octicons/question-16
      warning: octicons/alert-16
      failure: octicons/x-circle-16
      danger: octicons/zap-16
      bug: octicons/bug-16
      example: octicons/beaker-16
      quote: octicons/quote-16
    repo: fontawesome/brands/github
  logo: assets/eagle.png
  features:
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.indexes
    - search.suggest
    - toc.integrate
    - header.autohide
    - navigation.top

repo_url: https://github.com/nthaihoc/hoc-sphere

extra_css:
  - stylesheets/extra.css

extra_javascript:
  - javascripts/mathjax.js
  - https://unpkg.com/mathjax@3/es5/tex-mml-chtml.js

markdown_extensions:
  - md_in_html
  - attr_list
  - footnotes
  - meta
  - pymdownx.caret
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.critic
  - pymdownx.keys
  - pymdownx.mark 
  - pymdownx.tilde
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
  - tables
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format  

plugins:
  - macros
  - search

copyright: Copyright by Nguyen Thai Hoc

nav:
  - About Hoc: index.md
  - Hoc's Research Logs:
    - research-logs/index.md
    - Cervical Cancer Cytology: research-logs/cervical-cancer-cytology.md

  - Hoc's Course Notes:
    - course-notes/index.md
    - Machine Learning Course:
      - course-notes/csml/index.md
      - Introduction Intelligence Artificial and Machine Learning Basics: course-notes/csml/lecture01.md
      - Regression Analysis and Regression Algorithm: course-notes/csml/lecture02.md
  - Hoc's Playbook:
    - playbook/index.md
  - Hoc's Resources: 
    - resources/index.md

extra:
  analytics:
    provider: google
    property: G-S3GEPQ874N
  csml:
    lec02: https://drive.google.com/drive/folders/1-pePMyNJuVEXeTV1Nq1zQpGTNm0K3MGo?usp=drive_link
    code02: https://www.kaggle.com/code/nguyenthaihoc/01-linear-regression-gradient-descent
  research:
    resources: https://nthaihoc.github.io/hoc-sphere/research-logs/ccr-slides/
    slide01: None
        
    mate01: None 
    mate02: https://arxiv.org/pdf/2002.05709
    mate03: https://arxiv.org/pdf/2006.10029
    mate04: https://arxiv.org/pdf/1708.03888v3